FROM golang:1.23-alpine

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY . .

RUN go build -o /app/main ./cmd

EXPOSE 5000
ENV PORT=5000

CMD ["/app/main"]

#build image: docker build -f Dockerfile.prod -t go-gate-htmx-prod .
#start container: docker run -p 5000:5000 go-gate-htmx-prod 