FROM golang:1.23-alpine

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY . .

RUN go build -o /app/main ./cmd

EXPOSE 3000
ENV PORT=3000

CMD ["/app/main"]

#build image: docker -f Dockerfile.test -t go-gate-htmx-test .
#start container: docker run -p 3000:3000 go-gate-htmx-test 